[theme]
# Принудительно включаем темную (или серо-темную) тему для всех пользователей
base = "dark"
# Меняем стандартный красный "Streamlit" цвет на спокойный корпоративный синий
primaryColor = "#1f77b4"
